### ISSUE TITLE
Since image dtype is floating point, you must specify the data_range parameter.

### ISSUE THREAD

**Issue by Clemens-Honold** [SulekBartek/Anomaly_detection_MVtec#1]
hello,
thank you very much for this clear notebook!
the notebook works through to the penultimate cell without any problems.
in the juxtaposition comes the error: 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[46], line 5

----> 5 image_reconstructed_plot(model=model_loaded,
      6                         image_path=train_image_path,
      7                         transform=data_transform,
      8                         device=device)
     10 image_reconstructed_plot(model=model_loaded,
     11                         image_path=test_image_path_1,
     12                         transform=data_transform,
     13                         device=device)
     15 image_reconstructed_plot(model=model_loaded,
     16                         image_path=test_image_path_2,
     17                         transform=data_transform,
     18                         device=device)

Cell In[45], line 37, in image_reconstructed_plot(model, image_path, transform, device)
     35 img_old = np.array(original.squeeze(2))
     36 img_new = np.array(reconstructed.squeeze(2))
---> 37 _, S = ski_ssim(img_old, img_new, full=True, channel_axis=False)
     39 ax[2].imshow(1-S, vmax = 1, cmap='jet') 
     40 ax[2].set_title("SSIM")
...
    199     if im1.dtype != im2.dtype:
    200         warn("Inputs have mismatched dtypes. Setting data_range based on im1.dtype.",
    201              stacklevel=2)

ValueError: Since image dtype is floating point, you must specify the data_range parameter. Please read the documentation carefully (including the note). It is recommended that you always specify the data_range anyway.
---------------------------------------------------------------------------

how can i solve this?
thank you so much for your help!

**Comment by SulekBartek** [comment]
Hi, I have updated the notebook and solved this issue. Basically, since I added my code they've made changes in SSIM module, where the data_range parameter needs to be passed when pixel values are stored as float data types. So just simply add data_range in ssim function as I showed below:

`pixel_range = max(np.max(img_new), np.max(img_old)) - min(np.min(img_new), np.min(img_old))`
`_, S = ski_ssim(img_old, img_new, full=True, channel_axis=False, data_range=1) # data range set to 1 or pixel_range, depending on desired precision`

Thank you for catching that :D
